### ISSUE TITLE
Pressing a non-zoom key sometimes toggles the zoom

### ISSUE THREAD

**Issue by MarkinhosMLP** [trainb0y/FabriZoom#11]
Im using Left CTRL as ZOOM, but sometimes when i use the Right Alt (ALT GR) the zoom is randomly toggled for some reason

im using the last version, nothing shows up in the logs

**Comment by trainb0y** [comment]
Weird, I’ve never heard of anything like this happening before, and I don’t really know why it would. The mod just uses the fabric keybinding API; it doesn’t do anything nonstandard. 

Could you send a log anyway? I doubt it, but it might be being triggered by some other mod.
