### ISSUE TITLE
Add Traditional Chinese translation

### ISSUE THREAD

**Issue by StarsShine11904** [trainb0y/FabriZoom#12]
Hello author, I hope to add traditional Chinese translation to your module, I have prepared the file
After downloading the file, change the file format from .txt to .json

[zh_tw.txt](https://github.com/trainb0y/FabriZoom/files/10671085/zh_tw.txt)

_P.S. :Since I won't be using pull requests I can only put here_

**Comment by trainb0y** [comment]
Added with https://github.com/trainb0y/FabriZoom/commit/ad4d68c4ff538700b3195ec57251c033ad1fe742.
Thanks for the translation!

It will be in the next release.
