### ISSUE TITLE
Dirrect Quilt Users to QKL instead of Fabric Language Kotlin.

### ISSUE THREAD

**Issue by Mukul1127** [trainb0y/FabriZoom#13]
Quilt has their own Kotlin library which has compatibility for Fabric Language Kotlin

It is: [https://www.curseforge.com/minecraft/mc-mods/qkl](https://www.curseforge.com/minecraft/mc-mods/qkl)

**Comment by trainb0y** [comment]
Done with https://github.com/trainb0y/FabriZoom/commit/86f6651548f6c149e90e73f51e632a2a7ef28804
Will be updated on the mod list changes when I publish the 1.20 version
