### ISSUE TITLE
Error after trying build from gradlew

### ISSUE THREAD

**Issue by azzake** [trainb0y/FabriZoom#15]
I've wanted to build fabrizoom mod for version 1.20, but when I run the script using gradlew build I get this error. 
"could not determine the dependencies of task ':compileTestKotlin'. > Unknown Kotlin JVM target: 21". 
Is there any fix for that or do I need to change build.gradle.kts?

**Comment by trainb0y** [comment]
From a quick search, it looks like Kotlin 1.9.10 doesn't support Java 21. Updated to 1.9.20 with https://github.com/trainb0y/FabriZoom/commit/150ca38b160df8a3ad0f20e11eb70ab252c80fc7 and fixed Java target version, so it should work now.

Fair warning though; if you were trying to compile the Forge version, it isn't ready yet and still has some pretty major issues.
