### ISSUE TITLE
Fabric Loader 0.15.0 support

### ISSUE THREAD

**Issue by WithLithum** [trainb0y/FabriZoom#19]
The mod declares itself incompatible with the latest Fabric Loader (0.15.0). Is this intentional at the moment? If so, when will the support for Fabric Loader 0.15.0 be added?

**Comment by trainb0y** [comment]
That's definitely not intentional. I think it should work just fine on 0.15. I'll test it in a bit, and if everything works, I'll put out a version with fixed dependencies soon.

**Comment by trainb0y** [comment]
Fixed with https://github.com/trainb0y/FabriZoom/commit/ea714eadced2b9b749d20cb3c41b04a8dff96740 (`2.0.1`)
Bumped Fabric Loader to 0.15 though 0.14 should still work.
