### ISSUE TITLE
[Suggestion] Zooming sounds

### ISSUE THREAD

**Issue by MarkinhosMLP** [trainb0y/FabriZoom#3]
use the spyglass or other custom sound for zooming, like in the OkZoomer mod

**Comment by trainb0y** [comment]
Definitely worth looking into... if its relatively simple to do I'll add it.

**Comment by trainb0y** [comment]
Added a toggle for it with https://github.com/trainb0y/FabriZoom/commit/b17a0e79375d1574d61047c84d327eb68f133e0c
It will be in the next release, which will probably be soon:tm:

**Comment by trainb0y** [comment]
Soon? Not really. Now? Yes.
https://github.com/trainb0y/FabriZoom/releases/tag/1.2.0
